[project]
name = "CodeSnap"
version = "0.1.0"
description = "AI-powered code snapshot tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.0.0",
    "colorama",
    "pydantic>=2.0.0",
]

[project.scripts]
cs = "codesnap.main:main"
