[project]
name = "CodeSnap"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crispy-bootstrap4>=2024.10",
    "django>=5.1.7",
    "django-crispy-forms>=2.3",
    "furl>=2.1.4",
    "mysqlclient>=2.2.7",
]
